[project]
name = "nedogpt"
version = "1.0.0"
description = "NedoGPT for Telegram"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "aiogram>=3.30.0",
    "aiosqlite>=0.21.0",
    "alembic>=1.16.4",
    "jinja2>=3.1.6",
    "loguru>=0.7.3",
    "orjson>=3.11.4",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.1.0",
    "pyyaml>=6.0.2",
    "redis>=7.1.0",
    "tiktoken>=0.9.0",
    "unidecode>=1.4.0",
]
