"""model id as string

Revision ID: 1942f7dcbe69
Revises: 62a9741b9269
Create Date: 2025-11-22 23:14:04.770277

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import Column, Integer, String

# revision identifiers, used by Alembic.
revision: str = '1942f7dcbe69'
down_revision: Union[str, Sequence[str], None] = '62a9741b9269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'current_model_id',
        new_column_name='old_current_model_id'
    )
    op.add_column('users', Column("current_model_id", String(), default="18"))
    op.execute("UPDATE users SET current_model_id = CAST(old_current_model_id as STRING)")
    op.drop_column("users", "old_current_model_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'current_model_id',
        new_column_name='old_current_model_id'
    )
    op.add_column('users', Column("current_model_id", Integer(), default=2))
    op.execute("UPDATE users SET current_model_id = CAST(old_current_model_id as INTEGER)")
    op.drop_column("users", "old_current_model_id")
    # ### end Alembic commands ###
