"""add generations model

Revision ID: 6d326f6afa01
Revises: 1942f7dcbe69
Create Date: 2025-12-01 18:05:43.233163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d326f6afa01'
down_revision: Union[str, Sequence[str], None] = '1942f7dcbe69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('mood_id', sa.Integer(), nullable=True),
    sa.Column('parent_gen_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(current_timestamp)'), nullable=False),
    sa.ForeignKeyConstraint(['mood_id'], ['moods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_gen_id'], ['generations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generations')
    # ### end Alembic commands ###
